name: "Git Board Flow"
description: "Automates branch management, GitHub project linking, and issue/PR tracking with Git-Flow methodology."
author: "Landa Messenger"
inputs:
  debug:
    description: "Enable debug mode."
    default: "false"
  single-action:
    description: "Launch single actions."
    default: ""
  single-action-issue:
    description: "Issue target for executing single action."
    default: ""
  single-action-version:
    description: "Version target for executing single action."
    default: ""
  single-action-title:
    description: "Title target for executing single action."
    default: ""
  single-action-changelog:
    description: "Changelog target for executing single action."
    default: ""
  emoji-labeled-title:
    description: "Enable titles with emojis based on issue labels."
    default: "true"
  branch-management-launcher-label:
    description: "Label to trigger branch management actions."
    default: "branched"
  branch-management-always:
    description: "If true, ignores the branch-management-launcher-label requirement for running Git Board."
    default: "false"
  branch-management-emoji:
    description: "Emoji to indicate branched issues. It will be ignored if emoji-labeled-title is false."
    default: "🧑‍💻"
  docs-label:
    description: "Label to manage docs branches."
    default: "docs"
  documentation-label:
    description: "Label to manage docs branches."
    default: "documentation"
  chore-label:
    description: "Label to manage chore branches."
    default: "chore"
  maintenance-label:
    description: "Label to manage chore branches."
    default: "maintenance"
  hotfix-label:
    description: "Label to manage hotfix branches."
    default: "hotfix"
  release-label:
    description: "Label to manage release branches."
    default: "release"
  bug-label:
    description: "Label to indicate a bug type."
    default: "bug"
  bugfix-label:
    description: "Label to manage bugfix branches."
    default: "bugfix"
  feature-label:
    description: "Label to manage feature branches."
    default: "feature"
  enhancement-label:
    description: "Label to indicate a enhancement type."
    default: "enhancement"
  question-label:
    description: "Label to detect issues marked as questions."
    default: "question"
  help-label:
    description: "Label to detect help request issues."
    default: "help"
  deploy-label:
    description: "Label to detect deploy actions."
    default: "deploy"
  deployed-label:
    description: "Label to detect the deployed was."
    default: "deployed"
  priority-high-label:
    description: "Label to indicate a priority high."
    default: "priority: high"
  priority-medium-label:
    description: "Label to indicate a priority medium."
    default: "priority: medium"
  priority-low-label:
    description: "Label to indicate a priority low."
    default: "priority: low"
  size-xxl-label:
    description: "Label to indicate a task of size XXL."
    default: "size: XXL"
  size-xl-label:
    description: "Label to indicate a task of size XL."
    default: "size: XL"
  size-l-label:
    description: "Label to indicate a task of size L."
    default: "size: L"
  size-m-label:
    description: "Label to indicate a task of size M."
    default: "size: M"
  size-s-label:
    description: "Label to indicate a task of size S."
    default: "size: S"
  size-xs-label:
    description: "Label to indicate a task of size XS."
    default: "size: XS"
  size-xxl-threshold-lines:
    description: "Threshold for size XXL in lines."
    default: "1000"
  size-xxl-threshold-files:
    description: "Threshold for size XXL in files."
    default: "20"
  size-xxl-threshold-commits:
    description: "Threshold for size XXL in commits."
    default: "10"
  size-xl-threshold-lines:
    description: "Threshold for size XL in lines."
    default: "500"
  size-xl-threshold-files:
    description: "Threshold for size XL in files."
    default: "10"
  size-xl-threshold-commits:
    description: "Threshold for size XL in commits."
    default: "5"
  size-l-threshold-lines:
    description: "Threshold for size L in lines."
    default: "250"
  size-l-threshold-files:
    description: "Threshold for size L in files."
    default: "5"
  size-l-threshold-commits:
    description: "Threshold for size L in commits."
    default: "3"
  size-m-threshold-lines:
    description: "Threshold for size M in lines."
    default: "100"
  size-m-threshold-files:
    description: "Threshold for size M in files."
    default: "3"
  size-m-threshold-commits:
    description: "Threshold for size M in commits."
    default: "2"
  size-s-threshold-lines:
    description: "Threshold for size S in lines."
    default: "50"
  size-s-threshold-files:
    description: "Threshold for size S in files."
    default: "2"
  size-s-threshold-commits:
    description: "Threshold for size S in commits."
    default: "1"
  size-xs-threshold-lines:
    description: "Threshold for size XS in lines."
    default: "25"
  size-xs-threshold-files:
    description: "Threshold for size XS in files."
    default: "1"
  size-xs-threshold-commits:
    description: "Threshold for size XS in commits."
    default: "1"
  project-ids:
    description: "Comma-separated list of project IDs to link issues and pull requests."
    default: ""
  project-column-issue-created:
    description: "Name of the project column for new issues."
    default: "Todo"
  project-column-pull-request-created:
    description: "Name of the project column for new pull requests."
    default: "In Progress"
  project-column-issue-in-progress:
    description: "Name of the project column for in progress issues."
    default: "In Progress"
  project-column-pull-request-in-progress:
    description: "Name of the project column for in progress pull requests."
    default: "In Progress"

  issue-type-task:
    description: "Name of the issue type for tasks."
    default: "Task"
  issue-type-task-description:
    description: "Description of the issue type for tasks."
    default: "A specific piece of work or activity that needs to be completed to achieve project goals."
  issue-type-task-color:
    description: "Color of the issue type for tasks."
    default: "blue"

  issue-type-bug:
    description: "Name of the issue type for bugs."
    default: "Bug"
  issue-type-bug-description:
    description: "Description of the issue type for bugs."
    default: "An issue indicating a defect, error, or malfunction that needs to be investigated and fixed."
  issue-type-bug-color:
    description: "Color of the issue type for bugs."
    default: "orange"

  issue-type-feature:
    description: "Name of the issue type for features."
    default: "Feature"
  issue-type-feature-description:
    description: "Description of the issue type for features."
    default: "A new functionality, enhancement, or improvement requested for the project."
  issue-type-feature-color:
    description: "Color of the issue type for features."
    default: "green"

  issue-type-documentation:
    description: "Name of the issue type for documentation."
    default: "Documentation"
  issue-type-documentation-description:
    description: "Description of the issue type for documentation."
    default: "An update, addition, or correction needed in the project's documentation."
  issue-type-documentation-color:
    description: "Color of the issue type for documentation."
    default: "pink"

  issue-type-maintenance:
    description: "Name of the issue type for maintenance."
    default: "Maintenance"
  issue-type-maintenance-description:
    description: "Description of the issue type for maintenance."
    default: "A task related to refactoring, dependency updates, or other technical maintenance work."
  issue-type-maintenance-color:
    description: "Color of the issue type for maintenance."
    default: "purple"

  issue-type-hotfix:
    description: "Name of the issue type for hotfixes."
    default: "Hotfix"
  issue-type-hotfix-description:
    description: "Description of the issue type for hotfixes."
    default: "A quick and urgent fix applied to resolve a critical issue in production."
  issue-type-hotfix-color:
    description: "Color of the issue type for hotfixes."
    default: "red"

  issue-type-release:
    description: "Name of the issue type for releases."
    default: "Release"
  issue-type-release-description:
    description: "Description of the issue type for releases."
    default: "An issue representing a deployment or version release of the project."
  issue-type-release-color:
    description: "Color of the issue type for releases."
    default: "yellow"

  issue-type-question:
    description: "Name of the issue type for questions."
    default: "Question"
  issue-type-question-description:
    description: "Description of the issue type for questions."
    default: "A question or clarification request related to the project or its implementation."
  issue-type-question-color:
    description: "Color of the issue type for questions."
    default: "gray"

  issue-type-help:
    description: "Name of the issue type for help."
    default: "Help"
  issue-type-help-description:
    description: "Description of the issue type for help."
    default: "A request for support, guidance, or assistance regarding the project."
  issue-type-help-color:
    description: "Color of the issue type for help."
    default: "purple"

  issues-locale:
    description: "Locale of the issues."
    default: "en-US"
  pull-requests-locale:
    description: "Locale of the pull requests."
    default: "en-US"
  main-branch:
    description: "Name of the main branch (e.g., master)."
    default: "master"
  development-branch:
    description: "Name of the development branch (e.g., develop)."
    default: "develop"
  docs-tree:
    description: "Naming convention for docs branches."
    default: "docs"
  chore-tree:
    description: "Naming convention for chore branches."
    default: "chore"
  feature-tree:
    description: "Naming convention for feature branches."
    default: "feature"
  bugfix-tree:
    description: "Naming convention for bugfix branches."
    default: "bugfix"
  hotfix-tree:
    description: "Naming convention for hotfix branches."
    default: "hotfix"
  release-tree:
    description: "Naming convention for release branches."
    default: "release"
  images-on-issue:
    description: "Include images in issue comments."
    default: "true"
  images-on-pull-request:
    description: "Include images in pull request comments."
    default: "true"
  images-on-commit:
    description: "Include images in commit comments."
    default: "true"
  images-issue-automatic:
    description: "Image URLs to display in automatic action issue comments."
    default: ""
  images-issue-feature:
    description: "Image URLs to display in feature action issue comments."
    default: ""
  images-issue-bugfix:
    description: "Image URLs to display in bugfix action issue comments."
    default: ""
  images-issue-docs:
    description: "Image URLs to display in docs action issue comments."
    default: ""
  images-issue-chore:
    description: "Image URLs to display in chore action issue comments."
    default: ""
  images-issue-hotfix:
    description: "Image URLs to display in hotfix action issue comments."
    default: ""
  images-issue-release:
    description: "Image URLs to display in release action issue comments."
    default: ""
  images-pull-request-automatic:
    description: "Image URLs to display in automatic action pull request comments."
    default: ""
  images-pull-request-feature:
    description: "Image URLs to display in feature action pull request comments."
    default: ""
  images-pull-request-bugfix:
    description: "Image URLs to display in bugfix action pull request comments."
    default: ""
  images-pull-request-docs:
    description: "Image URLs to display in docs action pull request comments."
    default: ""
  images-pull-request-chore:
    description: "Image URLs to display in chore action pull request comments."
    default: ""
  images-pull-request-hotfix:
    description: "Image URLs to display in hotfix action pull request comments."
    default: ""
  images-pull-request-release:
    description: "Image URLs to display in release action pull request comments."
    default: ""
  images-commit-feature:
    description: "Image URLs to display in feature action commit comments."
    default: ""
  images-commit-bugfix:
    description: "Image URLs to display in bugfix action commit comments."
    default: ""
  images-commit-release:
    description: "Image URLs to display in release action commit comments."
    default: ""
  images-commit-automatic:
    description: "Image URLs to display in automatic action commit comments."
    default: ""
  images-commit-docs:
    description: "Image URLs to display in docs action commit comments."
    default: ""
  images-commit-chore:
    description: "Image URLs to display in chore action commit comments."
    default: ""
  images-commit-hotfix:
    description: "Image URLs to display in hotfix action commit comments."
    default: "" 
  commit-prefix-transforms:
    description: "List of transformations to apply sequentially for commit prefix generation. Options: replace-slash, replace-all, lowercase, uppercase, kebab-case, snake-case, camel-case, trim, remove-numbers, clean-dashes, etc."
    default: "replace-slash"
  reopen-issue-on-push:
    description: "Reopens a closed issue when changes are pushed to the branch associated with the issue."
    default: "true"
  release-workflow:
    description: "Release workflow for running release deploys."
    default: "release_workflow.yml"
  hotfix-workflow:
    description: "Hotfix workflow for running hotfix deploys."
    default: "hotfix_workflow.yml"
  desired-assignees-count:
    description: "The number of assignees desired for the issue or pull request. If set to 0, no assignees will be added. If the number exceeds the available members, all members will be assigned. Max 10."
    default: "1"
  desired-reviewers-count:
    description: "The number of reviewers desired for the pull request. If set to 0, no reviewers will be added. If the number exceeds the available members, all members will be reviewers. Max 15."
    default: "1"
  merge-timeout:
    description: "The timeout for the merge workflow in seconds. If set to 0, the merge will not be timed out."
    default: "600"
  token:
    description: "Fine-grained personal access token for branch and project operations"
    required: true
  classic-token:
    description: "Classic token for authentication with GitHub Container Registry"
    default: ""
  supabase-key:
    description: "Supabase key for AI operations."
    default: ""
  supabase-url:
    description: "Supabase URL for AI operations."
    default: ""
  openrouter-api-key:
    description: "OpenRouter API key for AI operations."
    default: ""
  openrouter-model:
    description: "OpenRouter model for AI operations."
    default: "deepseek/deepseek-chat"
  openrouter-provider-order:
    description: "Comma-separated list of provider names to try in order."
    default: ""
  openrouter-provider-allow-fallbacks:
    description: "Whether to allow backup providers when the primary is unavailable."
    default: "true"
  openrouter-provider-require-parameters:
    description: "Only use providers that support all parameters in the request."
    default: "false"
  openrouter-provider-data-collection:
    description: "Control whether to use providers that may store data (allow/deny)."
    default: "allow"
  openrouter-provider-ignore:
    description: "Comma-separated list of provider names to skip."
    default: ""
  openrouter-provider-quantizations:
    description: "Comma-separated list of quantization levels to filter by (e.g., int4, int8, fp4, fp6, fp8, fp16, bf16, fp32)."
    default: ""
  openrouter-provider-sort:
    description: "Sort providers by price, throughput, or latency."
    default: "price"
  ai-pull-request-description:
    description: "Enable AI-powered automatic updates for pull request descriptions."
    default: "false"
  ai-ignore-files:
    description: "Comma-separated list of files to ignore for AI operations."
    default: ""
  ai-members-only:
    description: "Restrict AI features to only organization/project members."
    default: "true"
  docker-container-name:
    description: "Name of the Docker container to use."
    default: "git-board-flow"
  docker-domain:
    description: "Domain of the Docker container to use."
    default: "localhost"
  docker-port:
    description: "Port of the Docker container to use."
    default: "8000"
  docker-cache-os:
    description: "OS of the Docker container to cache. Valid values: ubuntu-any-value, macos-any-value, windows-any-value"
    default: "ubuntu-latest"
  docker-cache-arch:
    description: "Architecture of the Docker container to cache. Valid values: amd64, arm64, arm/v7, 386, s390x, ppc64le"
    default: "amd64"
runs:
  using: "node20"
  main: "build/github_action/index.js"
branding:
  icon: "git-branch"
  color: "gray-dark"
