name: "Git Board Flow"
description: "Automates branch management, GitHub project linking, and issue/PR tracking with Git-Flow methodology."
author: "Landa Messenger"
inputs:
  single-action:
    description: "Launch single actions."
    default: ""
  single-action-issue:
    description: "Issue target for executing single action."
    default: ""
  emoji-labeled-title:
    description: "Enable titles with emojis based on issue labels."
    default: "true"
  branch-management-launcher-label:
    description: "Label to trigger branch management actions."
    default: "branched"
  branch-management-always:
    description: "If true, ignores the branch-management-launcher-label requirement for running Git Board."
    default: "false"
  branch-management-emoji:
    description: "Emoji to indicate branched issues. It will be ignored if emoji-labeled-title is false."
    default: "🧑‍💻"
  hotfix-label:
    description: "Label to manage hotfix branches."
    default: "hotfix"
  release-label:
    description: "Label to manage release branches."
    default: "release"
  bug-label:
    description: "Label to indicate a bug type."
    default: "bug"
  bugfix-label:
    description: "Label to manage bugfix branches."
    default: "bugfix"
  feature-label:
    description: "Label to manage feature branches."
    default: "feature"
  enhancement-label:
    description: "Label to indicate a enhancement type."
    default: "enhancement"
  question-label:
    description: "Label to detect issues marked as questions."
    default: "question"
  help-label:
    description: "Label to detect help request issues."
    default: "help"
  deploy-label:
    description: "Label to detect deploy actions."
    default: "deploy"
  deployed-label:
    description: "Label to detect the deployed was."
    default: "deployed"
  project-urls:
    description: "Comma-separated list of project URLs to link issues and pull requests."
    default: ""
  main-branch:
    description: "Name of the main branch (e.g., master)."
    default: "master"
  development-branch:
    description: "Name of the development branch (e.g., develop)."
    default: "develop"
  feature-tree:
    description: "Naming convention for feature branches."
    default: "feature"
  bugfix-tree:
    description: "Naming convention for bugfix branches."
    default: "bugfix"
  hotfix-tree:
    description: "Naming convention for hotfix branches."
    default: "hotfix"
  release-tree:
    description: "Naming convention for release branches."
    default: "release"
  images-issue-automatic:
    description: "Image URLs to display in automatic action issue comments."
    default: ""
  images-issue-feature:
    description: "Image URLs to display in feature action issue comments."
    default: ""
  images-issue-bugfix:
    description: "Image URLs to display in bugfix action issue comments."
    default: ""
  images-issue-hotfix:
    description: "Image URLs to display in hotfix action issue comments."
    default: ""
  images-issue-release:
    description: "Image URLs to display in release action issue comments."
    default: ""
  images-pull-request-automatic:
    description: "Image URLs to display in automatic action pull request comments."
    default: ""
  commit-prefix-builder:
    description: "Enable commit prefix generation."
    default: ""
  reopen-issue-on-push:
    description: "Reopens a closed issue when changes are pushed to the branch associated with the issue."
    default: "true"
  release-workflow:
    description: "Release workflow for running release deploys."
    default: "release_workflow.yml"
  hotfix-workflow:
    description: "Hotfix workflow for running hotfix deploys."
    default: "release"
  desired-assignees-count:
    description: "The number of assignees desired for the issue or pull request. If set to 0, no assignees will be added. If the number exceeds the available members, all members will be assigned. Max 10."
    default: "1"
  desired-reviewers-count:
    description: "The number of reviewers desired for the pull request. If set to 0, no reviewers will be added. If the number exceeds the available members, all members will be reviewers. Max 15."
    default: "1"
  merge-timeout:
    description: "The timeout for the merge workflow in seconds. If set to 0, the merge will not be timed out."
    default: "600"
  github-token:
    description: "GitHub token for branch and project operations within the repository scope."
    required: true
  github-token-personal:
    description: "GitHub PAT for extended operations on commits, branches, and projects."
    required: true
  openai-api-key:
    description: "OpenAI API key for AI operations."
    default: ""
  ai-pull-request-description:
    description: "Enable AI-powered automatic updates for pull request descriptions."
    default: "false"
  ai-members-only:
    description: "Restrict AI features to only organization/project members."
    default: "true"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "git-branch"
  color: "gray-dark"
