name: ðŸš€ Release Issue

description: Request a new release for git-board-flow (only team members)
title: "<YOUR TITLE HERE>"
labels: ["release"]
body:
  - type: markdown
    attributes:
      value: |
        ### âš ï¸ Disclaimer
        > **Only members of the git-board-flow team can create release issues.**
        > Any release issue created by someone outside the team will be closed automatically.

        ---

  - type: input
    id: version
    attributes:
      label: Release Version
      description: |
        Specify the version number for the release (e.g., 1.2.3).
      placeholder: "e.g., 1.2.3"
    validations:
      required: true

  - type: textarea
    id: changelog
    attributes:
      label: Changelog
      description: |
        Provide a summary of the changes to be included in this release. Highlight any major features, fixes, or updates.
      placeholder: "Add a concise changelog here."
    validations:
      required: true

  - type: dropdown
    id: release_type
    attributes:
      label: Release Type
      description: |
        Indicate the type of release.
      options:
        - Major
        - Minor
        - Patch
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: Pre-Release Checklist
      description: |
        List any pre-release tasks or checks that need to be completed before the release can be finalized.
      placeholder: |
        Example:
        - [ ] Update documentation
        - [ ] Ensure tests pass
        - [ ] Code review completed
      render: task-list
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: |
        Add any additional details or context about this release request.
      placeholder: "Anything else to note?"
