name: Git Board Flow - Vector Action

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!develop'

jobs:
  git-board-vector-action:
    name: Git Board - Vector Action
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Setup docker and docker-compose (missing on MacOS)
        if: runner.os == 'macos'
        run: |
          brew install --cask docker
          brew install colima
          brew services start colima

      - name: Set up DOCKER_HOST as output
        id: docker-env
        run: |
          echo "docker_host=unix://${HOME}/.colima/default/docker.sock" >> $GITHUB_OUTPUT

      - name: Run Vector Action
        uses: ./
        env:
          DOCKER_HOST: ${{ steps.docker-env.outputs.docker_host }}
        with:
          single-action: vector_action
          debug: ${{ vars.DEBUG }}
          firebase-config: ${{ secrets.FIREBASE_CONFIG }}
          project-ids: 2
          openrouter-api-key: ${{ secrets.OPEN_ROUTER_API_KEY }}
          openrouter-model: ${{ vars.OPEN_ROUTER_MODEL }}
          token: ${{ secrets.PAT }}
