name: Git Board Flow - Vector Action

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!develop'

jobs:
  git-board-vector-action:
    name: Git Board - Vector Action
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - uses: ./
        with:
          single-action: vector_action
          debug: ${{ vars.DEBUG }}
          firebase-config: ${{ secrets.FIREBASE_CONFIG }}
          project-ids: 2
          openrouter-api-key: ${{ secrets.OPEN_ROUTER_API_KEY }}
          openrouter-model: ${{ vars.OPEN_ROUTER_MODEL }}
          token: ${{ secrets.PAT }}
