name: Git Board Flow - Commit

on:
  push:
    branches:
      - '**'

jobs:
  git-board-commits:
    name: Git Board - Commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Git Board - Commit
        uses: ./
        with:
          debug: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-token-personal: ${{ secrets.REPO_PAT }}
